export type SystemNode = { id: string; label: string; kind: "input" | "ai" | "logic" | "data" | "action"; x: number; y: number; detail: string };
export const systemNodes: SystemNode[] = [
  { id: "website", label: "Website / form", kind: "input", x: 25, y: 120, detail: "Captures a structured service request from a website or form." },
  { id: "voice", label: "AI call agent", kind: "ai", x: 25, y: 210, detail: "Handles customer conversations and sends structured booking requests into the automation engine." },
  { id: "message", label: "Email / SMS", kind: "input", x: 25, y: 300, detail: "Brings customer enquiries from communication channels into the same request flow." },
  { id: "whatsapp", label: "WhatsApp", kind: "input", x: 25, y: 390, detail: "A messaging entry point for customer requests and contact preferences." },
  { id: "manual", label: "Manual request", kind: "input", x: 25, y: 480, detail: "Allows a team member to initiate the same operational workflow." },
  { id: "webhook", label: "Webhook", kind: "input", x: 215, y: 210, detail: "Receives request payloads and starts the central n8n workflow." },
  { id: "normalize", label: "Normalize request", kind: "logic", x: 215, y: 300, detail: "Validates required fields and normalizes customer, service and date information." },
  { id: "intent", label: "Understand intent", kind: "ai", x: 215, y: 390, detail: "Identifies whether the customer needs a new booking, a change or a cancellation." },
  { id: "qualify", label: "Qualify lead", kind: "ai", x: 405, y: 120, detail: "Checks service needs against business rules before progressing a request." },
  { id: "route", label: "Route request", kind: "logic", x: 405, y: 300, detail: "Branches a normalized request into booking, rescheduling or cancellation workflows." },
  { id: "preference", label: "Contact preference", kind: "logic", x: 405, y: 480, detail: "Selects the appropriate communication channel for the customer." },
  { id: "supabase", label: "Supabase", kind: "data", x: 595, y: 120, detail: "Central data layer for leads, appointments and availability." },
  { id: "lead", label: "Create / update lead", kind: "data", x: 595, y: 210, detail: "Keeps the lead record linked to the incoming enquiry." },
  { id: "lookup", label: "Find appointment", kind: "data", x: 595, y: 390, detail: "Retrieves the existing appointment before a change or cancellation." },
  { id: "crm", label: "Customer / CRM", kind: "data", x: 595, y: 570, detail: "Keeps customer and appointment references connected across operations." },
  { id: "day", label: "Validate day", kind: "logic", x: 785, y: 120, detail: "Checks the requested date against the business schedule." },
  { id: "availability", label: "Check availability", kind: "logic", x: 785, y: 210, detail: "Queries business availability and existing appointments before allowing a booking." },
  { id: "conflict", label: "Detect conflict", kind: "logic", x: 785, y: 300, detail: "Branches when a requested time clashes with an existing appointment." },
  { id: "reschedule", label: "Reschedule?", kind: "logic", x: 785, y: 390, detail: "Checks that an existing booking can be moved before updating its date and time." },
  { id: "cancel", label: "Cancel request?", kind: "logic", x: 785, y: 480, detail: "Validates a cancellation and routes the associated record and calendar updates." },
  { id: "book", label: "Create appointment", kind: "action", x: 975, y: 120, detail: "Creates an appointment only after the requested slot passes validation." },
  { id: "alternative", label: "Alternative slot", kind: "logic", x: 975, y: 300, detail: "Returns another scheduling path when the original time is unavailable." },
  { id: "update", label: "Update appointment", kind: "data", x: 975, y: 390, detail: "Updates an existing appointment after rescheduling checks." },
  { id: "remove", label: "Cancel appointment", kind: "data", x: 975, y: 480, detail: "Updates the appointment state and initiates calendar cleanup." },
  { id: "calendar", label: "Google Calendar", kind: "action", x: 1165, y: 120, detail: "Creates or updates the calendar event associated with the appointment." },
  { id: "confirm", label: "Confirmation", kind: "action", x: 1355, y: 120, detail: "Sends the customer the relevant booking details through their contact channel." },
  { id: "calendarupdate", label: "Sync calendar", kind: "action", x: 1165, y: 390, detail: "Synchronizes a changed appointment with its calendar event." },
  { id: "calendardelete", label: "Remove event", kind: "action", x: 1165, y: 480, detail: "Removes the calendar event associated with a cancelled appointment." },
  { id: "status", label: "Status update", kind: "action", x: 1355, y: 390, detail: "Communicates a rescheduling or cancellation outcome to the customer." },
  { id: "remind", label: "Reminder", kind: "action", x: 1355, y: 210, detail: "Connects appointment information to a reminder workflow." },
  { id: "followup", label: "Follow-up", kind: "action", x: 1355, y: 300, detail: "Continues customer communication after the initial booking interaction." },
  { id: "reactivate", label: "Reactivation", kind: "action", x: 1165, y: 570, detail: "Uses eligible customer records to support a relevant future outreach workflow." },
  { id: "reply", label: "Webhook response", kind: "action", x: 975, y: 570, detail: "Returns the workflow outcome to the requesting system." },
];
export const systemEdges: [string, string][] = [
  ["website","webhook"],["voice","webhook"],["message","webhook"],["whatsapp","webhook"],["manual","webhook"],
  ["webhook","normalize"],["normalize","intent"],["intent","route"],["intent","qualify"],["qualify","lead"],
  ["lead","supabase"],["route","day"],["day","availability"],["supabase","availability"],["availability","conflict"],
  ["conflict","book"],["conflict","alternative"],["alternative","reply"],["book","calendar"],["book","lead"],
  ["calendar","confirm"],["confirm","remind"],["remind","followup"],["route","lookup"],["lookup","reschedule"],
  ["lookup","cancel"],["reschedule","update"],["update","calendarupdate"],["cancel","remove"],["remove","calendardelete"],
  ["calendarupdate","status"],["calendardelete","status"],["route","preference"],["preference","crm"],
  ["crm","reactivate"],["reactivate","followup"],["update","reply"],["remove","reply"],
];
export const signalRoute = ["voice","webhook","normalize","intent","route","day","availability","conflict","book","calendar","confirm","remind","followup"];
